#!/bin/bash

ip_add_list_file=$1


tempdir=`mktemp -d /var/tmp/LAMOS.pingtest.result.XXX`
date=`date`

while read addr ; do ( ping -c 1 -w 1 $addr > /dev/null 2>&1 ; if [ $? == 0 ] ; then touch $tempdir/$addr ; fi ) &  done < $ip_add_list_file
wait
while read addr ; do if [ -e $tempdir/$addr ] ; then echo "$date;Pass;$addr" ; else echo "$date;Fail;$addr" ; fi done < $ip_add_list_file
rm -r $tempdir > /dev/null 2>&1
